start:
dispc "Hello world!";
ST R0,5,R31;
LD R31,5,R1;
ADD R0,R1,R2;
beq R2,start,R1;

failedLD: db "Failed LD\n";
failedST: db "Failed ST\n";
failedDISP: db "Failed DISP\n";
failedJMP: db "Failed JMP\n";
failedBEQ: db "Failed BEQ\n";
failedBNE: db "Failed BNE\n";
failedDISPC: db "Failed DISPC\n";
failedLDR: db "Failed LDR\n";
failedADD: db "Failed ADD\n";
failedSUB: db "Failed SUB\n";
failedMUL: db "Failed MUL\n";
failedDIV: db "Failed DIV\n";
failedCMPEQ: db "Failed CMPEQ\n";
failedCMPLT: db "Failed CMPLT\n";
failedCMPLE: db "Failed CMPLE\n";
failedAND: db "Failed AND\n";
failedOR: db "Failed OR\n";
failedXOR: db "Failed XOR\n";
failedXNOR: db "Failed XNOR\n";
failedSHL: db "Failed SHL\n";
failedSHR: db "Failed SHR\n";
failedSRA: db "Failed SRA\n";
failedADDC: db "Failed ADDC\n";
failedSUBC: db "Failed SUBC\n";
failedMULC: db "Failed MULC\n";
failedDIVC: db "Failed DIVC\n";
failedCMPEQC: db "Failed CMPEQC\n";
failedCMPLTC: db "Failed CMPLTC\n";
failedCMPLEC: db "Failed CMPLEC\n";
failedANDC: db "Failed ANDC\n";
failedORC: db "Failed ORC\n";
failedXORC: db "Failed XORC\n";
failedXNORC: db "Failed XNORC\n";
failedSHLC: db "Failed SHLC\n";
failedSHRC: db "Failed SHRC\n";
failedSRAC: db "Failed SRAC\n";

